# Generated by Django 3.0.6 on 2020-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommFood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPdts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.TextField(default='per kg'),
        ),
    ]
