# Generated by Django 3.0.6 on 2020-06-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommFood', '0006_auto_20200608_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='test-pdt'),
        ),
    ]
