# Generated by Django 3.0.6 on 2020-06-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommFood', '0007_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
